### ISSUE TITLE
デザインの相談

### ISSUE THREAD

**Issue by shoma-mano** [shoma-mano/share-issue#1]
## ※完了したタスクから削除していきます

・IT重説の日程の表示
<img width="1150" alt="image" src="https://github.com/shoma-mano/share-issue/assets/65682253/8af7687a-4ca3-4586-b0f6-f358c52e4dcf">

・ファイルアップロード
<img width="973" alt="image" src="https://github.com/user-attachments/assets/7c3c2294-f7e5-4df7-98b1-6cff192c2470">

**Comment by SENOSuit** [comment]
@shoma-mano 
>・ある程度複雑な手続きのステップのUIをどうするか
こちらのデザイン案を起こしてみましたので、ご確認ください。
https://www.figma.com/design/2HjSouSB1UzWPVZ0a7vwv4/ShataX?node-id=20607-240&t=4Xt9wYgfOHrRtBKJ-4

**Comment by shoma-mano** [comment]
良い感じだと思います。ファイルのプレビューを表示するパターンも欲しいです。

**Comment by SENOSuit** [comment]
@shoma-mano 
こちらもデザイン案を起こしてみましたので、ご確認ください。
https://www.figma.com/design/2HjSouSB1UzWPVZ0a7vwv4/ShataX?node-id=20849-559&t=CG9rFeyK3IOgek2Q-4

**Comment by SENOSuit** [comment]
@shoma-mano 
社員一覧、従業員の招待系のデザイン案を起こしましたので、ご確認ください。
https://www.figma.com/design/2HjSouSB1UzWPVZ0a7vwv4/ShataX?node-id=20849-817&t=CG9rFeyK3IOgek2Q-4
https://www.figma.com/design/2HjSouSB1UzWPVZ0a7vwv4/ShataX?node-id=20849-1154&t=CG9rFeyK3IOgek2Q-4

**Comment by shoma-mano** [comment]
良いと思います！細かいので後でいいですが、ボタンにホバーした時の色とかも欲しいです!

**Comment by shoma-mano** [comment]
![image](https://github.com/shoma-mano/share-issue/assets/65682253/50d53ee5-39ae-4ff9-9ef1-25e1f26bb7c0)
手続き画面の固定部分ですが、プログレスバーをここらへんに移動するなどして、高さを小さくして欲しいです。

**Comment by shoma-mano** [comment]
<img width="849" alt="スクリーンショット 2024-05-17 16 58 37" src="https://github.com/shoma-mano/share-issue/assets/65682253/452b461b-53c7-44eb-bdec-3d9dd74d7a48">

**Comment by shoma-mano** [comment]
見た目は全然変えて良いのですが、フィルターの機能はこんな感じのUIです

<img width="1162" alt="スクリーンショット 2024-05-17 18 27 49" src="https://github.com/shoma-mano/share-issue/assets/65682253/c89e38b5-f5ed-4a31-bdb0-a26852c554d5">


<img width="1171" alt="image" src="https://github.com/shoma-mano/share-issue/assets/65682253/1ea2eedd-bf4e-461f-9b98-df1c59d1173c">

**Comment by aoi-tori** [comment]
<img width="1840" alt="Screenshot 2024-06-25 at 12 59 50" src="https://github.com/shoma-mano/share-issue/assets/81035310/569f9ab0-b60a-4d65-8f7c-fa7ecb49bef1">

「社宅規定の選択は必須でないほうが良い」というフィードバックがあったので、そのように修正をお願いしたいです！

**Comment by aoi-tori** [comment]
手続き一覧ページの修正をお願いします！
<img width="1840" alt="Screenshot 2024-06-18 at 14 50 08" src="https://github.com/shoma-mano/share-issue/assets/81035310/dc4365da-596c-41b0-968e-e965fd7931e8">

**Comment by aoi-tori** [comment]
<img width="1840" alt="Screenshot 2024-06-25 at 17 44 56" src="https://github.com/shoma-mano/share-issue/assets/81035310/fd333366-a55a-4b90-ad97-27dcdafcfd41">
契約書類を性質によって分類して表示したほうが良いかもしれない
（この二つの他に表示予定のIT重説等の同意書は、署名は不要だが記名は必要。これも分けるべきか要検討）
